# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dev/proj/cpp/overload

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dev/proj/cpp/overload

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dev/proj/cpp/overload/CMakeFiles /home/dev/proj/cpp/overload/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dev/proj/cpp/overload/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named projx

# Build rule for target.
projx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 projx
.PHONY : projx

# fast build rule for target.
projx/fast:
	$(MAKE) -f CMakeFiles/projx.dir/build.make CMakeFiles/projx.dir/build
.PHONY : projx/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/projx.dir/build.make CMakeFiles/projx.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/projx.dir/build.make CMakeFiles/projx.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/projx.dir/build.make CMakeFiles/projx.dir/main.cpp.s
.PHONY : main.cpp.s

matrix.o: matrix.cpp.o
.PHONY : matrix.o

# target to build an object file
matrix.cpp.o:
	$(MAKE) -f CMakeFiles/projx.dir/build.make CMakeFiles/projx.dir/matrix.cpp.o
.PHONY : matrix.cpp.o

matrix.i: matrix.cpp.i
.PHONY : matrix.i

# target to preprocess a source file
matrix.cpp.i:
	$(MAKE) -f CMakeFiles/projx.dir/build.make CMakeFiles/projx.dir/matrix.cpp.i
.PHONY : matrix.cpp.i

matrix.s: matrix.cpp.s
.PHONY : matrix.s

# target to generate assembly for a file
matrix.cpp.s:
	$(MAKE) -f CMakeFiles/projx.dir/build.make CMakeFiles/projx.dir/matrix.cpp.s
.PHONY : matrix.cpp.s

vector.o: vector.cpp.o
.PHONY : vector.o

# target to build an object file
vector.cpp.o:
	$(MAKE) -f CMakeFiles/projx.dir/build.make CMakeFiles/projx.dir/vector.cpp.o
.PHONY : vector.cpp.o

vector.i: vector.cpp.i
.PHONY : vector.i

# target to preprocess a source file
vector.cpp.i:
	$(MAKE) -f CMakeFiles/projx.dir/build.make CMakeFiles/projx.dir/vector.cpp.i
.PHONY : vector.cpp.i

vector.s: vector.cpp.s
.PHONY : vector.s

# target to generate assembly for a file
vector.cpp.s:
	$(MAKE) -f CMakeFiles/projx.dir/build.make CMakeFiles/projx.dir/vector.cpp.s
.PHONY : vector.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... projx"
	@echo "... rebuild_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... matrix.o"
	@echo "... matrix.i"
	@echo "... matrix.s"
	@echo "... vector.o"
	@echo "... vector.i"
	@echo "... vector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

